/* upcr_config.h.  Generated from upcr_config.h.in by configure.  */
/* upcr_config.h.in.  Generated from configure.in by autoheader.  */
/*
 * UPC Runtime common configuration template--parsed though autoconf 
 * to generate upcr_config.h.
 *  -- note: base file is 'acconfig.h'--make any changes there!
 *
 * Notes: 
 *  -- All public symbols should use UPCR_ ("UPC Runtime") prefix.
 *  -- All internal symbols should use UPCRI_ ("UPC Runtime internal") prefix.
 *	 -- Preprocessor symbols w/o this are autoconf-generated.
 *  -- We rely heavily on the GASNet config to avoid duplication.
 *
 * $Source: bitbucket.org:berkeleylab/upc-runtime.git/acconfig.h $
 */

#ifndef UPCR_CONFIG_H
#define UPCR_CONFIG_H

/* Everything above this is passed though autoconf verbatim */

#define UPCR_VERSION "2020.4.0"
#define UPCR_RUNTIME_SPEC_MAJOR 3
#define UPCR_RUNTIME_SPEC_MINOR 14
#define UPCRI_SYSTEM_NAME "ubuntu"
#define UPCRI_SYSTEM_TUPLE "x86_64-unknown-linux-gnu"
#define UPCRI_CONFIGURE_ARGS "'--with-translator=http://upc-translator.lbl.gov/upcc-2020.4.0.cgi' '--enable-debug' '--prefix=/usr/local/berkeley_upc/dbg' '--with-multiconf-magic=dbg'"
#define UPCRI_BUILD_ID "Tue Dec  8 15:08:54 -03 2020 beatrizdejesus"

/* Whether this copy of the runtime is being used as a target for the gccupc
 * binary UPC compiler */
/* #undef UPCRI_USING_GCCUPC */

/* Whether this copy of the runtime supports init sections generated by
 * the gccupc compilerm, or static copy must be done */
/* #undef UPCRI_USING_GCCUPC_INIT_SECTION */
/* #undef UPCRI_USING_GCCUPC_INIT_STATIC_COPY */

/* Whether this copy of the runtime is being used as a target for the Clang
 * binary UPC compiler */
/* #undef UPCRI_USING_CUPC */

/* Whether this copy of the runtime is being used as a target for the
 * clang-upc2c source-to-source translator */
/* #undef UPCRI_USING_CUPC2C */

/* Define if you wish to extend printf (and friends) with  %S/%P format 
 * specifiers for shared/pshared pointers (requires glibc) */
/* #undef UPCR_EXTEND_PRINTF */

/* Whether or not to enable the GASP instrumentation hooks */
/* #undef UPCRI_GASP */

/* Whether or not to use the libc malloc to manage the umalloc heap metadata */
#define UMALLOC_EXTERNAL_METADATA 1

/* Whether or not to use the more efficient 'packed' shared pointer representation */
#define UPCRI_PACKED_SPTR 1

/* Whether or not to use the 'struct' shared pointer representation */
/* #undef UPCRI_STRUCT_SPTR */

/* 'struct' shared pointer configuration information (when available) */
/* #undef UPCRI_STRUCT_SPTR_ADDR_TYPE */
/* #undef UPCRI_STRUCT_SPTR_THREAD_TYPE */
/* #undef UPCRI_STRUCT_SPTR_PHASE_TYPE */
/* #undef UPCRI_STRUCT_SPTR_ADDR_FIELD */
/* #undef UPCRI_STRUCT_SPTR_THREAD_FIELD */
/* #undef UPCRI_STRUCT_SPTR_PHASE_FIELD */
/* #undef UPCRI_STRUCT_SPTR_ALIGN */

/* Set if the shoared pointer has the address field first */
/* #undef UPCRI_SPTR_ADDR_FIRST */

/* Whether or not to enable the pshared symmetric pointer variant of shared pointers */
/* #undef UPCRI_SYMMETRIC_SPTR */

/* configure-selected bit distribution for the packed shared pointer representation */
/* #undef UPCRI_PHASE_BITS_OVERRIDE */
/* #undef UPCRI_THREAD_BITS_OVERRIDE */
/* #undef UPCRI_ADDR_BITS_OVERRIDE */

/* Whether to implement the (currently experimental) "strict hook" */
#define UPCRI_STRICT_HOOK_ENABLED 1

/* Whether to provide a 64-bit upc_off_t */
#define BUPC_IO_64 1

/* have usable pthread_mutexattr_setpshared() */
#define HAVE_PTHREAD_MUTEXATTR_SETPSHARED 1

/* gcc built-ins */
#define HAVE_BUILTIN_HUGE_VAL 1
#define HAVE_BUILTIN_HUGE_VALF 1
#define HAVE_BUILTIN_HUGE_VALL 1
#define HAVE_BUILTIN_INF 1
#define HAVE_BUILTIN_INFF 1
#define HAVE_BUILTIN_NAN 1
#define HAVE_BUILTIN_NANF 1

/* __thread attribute works for pthread-local data */
#define HAVE_GCC_TLS_SUPPORT 1

/* supports __attribute((__aligned__(16))) */
/* #undef HAVE_GCC_ATTRIBUTE_ALIGNED */

/* mcleanup() gprof function */
#define HAVE_MCLEANUP 1

/* monitor_signal() Compaq profiling function */
/* #undef HAVE_MONITOR_SIGNAL */

/* monitor(0) AIX profiling function */
/* #undef HAVE_MONITOR */

/* monitor(0,0,0,0,0) Solaris profiling function */
/* #undef HAVE_MONITOR5 */

/* PGI rouexit profile cleanup function */
/* #undef HAVE_ROUEXIT */

/* C program stack grows up */
/* #undef UPCRI_STACK_GROWS_UP */

/* have attribute(cleanup) support */
#define UPCRI_HAVE_ATTRIBUTE_CLEANUP 1

/* portable inttypes support */
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_SYS_TYPES_H 1
#define COMPLETE_INTTYPES_H 1
#define COMPLETE_STDINT_H 1
#define COMPLETE_SYS_TYPES_H 0

/* support for coercing __uint128_t through Berkeley UPC translator */
#define UPCRI_NEED_UINT128_T 1

/* Everything below this is passed though autoconf verbatim */

/* Define to 1 if you have the <alloca.h> header file. */
#define HAVE_ALLOCA_H 1

/* Define to 1 if you have the <assert.h> header file. */
#define HAVE_ASSERT_H 1

/* Define to 1 if you have the <bits/floatn.h> header file. */
#define HAVE_BITS_FLOATN_H 1

/* Define to 1 if you have the <byteswap.h> header file. */
#define HAVE_BYTESWAP_H 1

/* Define to 1 if you have the `bzero' function. */
#define HAVE_BZERO 1

/* Define to 1 if you have the <complex.h> header file. */
#define HAVE_COMPLEX_H 1

/* Define to 1 if you have the <ctype.h> header file. */
#define HAVE_CTYPE_H 1

/* Define to 1 if you have the <errno.h> header file. */
#define HAVE_ERRNO_H 1

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the <fenv.h> header file. */
#define HAVE_FENV_H 1

/* Define to 1 if you have the <float.h> header file. */
#define HAVE_FLOAT_H 1

/* Define to 1 if you have the `getpagesize' function. */
#define HAVE_GETPAGESIZE 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <iso646.h> header file. */
#define HAVE_ISO646_H 1

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if you have the <locale.h> header file. */
#define HAVE_LOCALE_H 1

/* Define to 1 if you have the <malloc.h> header file. */
#define HAVE_MALLOC_H 1

/* Define to 1 if you have the <math.h> header file. */
#define HAVE_MATH_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <mon.h> header file. */
/* #undef HAVE_MON_H */

/* Define to 1 if you have the <netinet/tcp.h> header file. */
#define HAVE_NETINET_TCP_H 1

/* Define to 1 if you have the <printf.h> header file. */
#define HAVE_PRINTF_H 1

/* Define to 1 if you have the `pthread_attr_setguardsize' function. */
#define HAVE_PTHREAD_ATTR_SETGUARDSIZE 1

/* Define to 1 if you have the `pthread_setconcurrency' function. */
#define HAVE_PTHREAD_SETCONCURRENCY 1

/* Define to 1 if you have the <setjmp.h> header file. */
#define HAVE_SETJMP_H 1

/* Define to 1 if you have the <signal.h> header file. */
#define HAVE_SIGNAL_H 1

/* Define to 1 if you have the <stdarg.h> header file. */
#define HAVE_STDARG_H 1

/* Define to 1 if you have the <stdbool.h> header file. */
#define HAVE_STDBOOL_H 1

/* Define to 1 if you have the <stddef.h> header file. */
#define HAVE_STDDEF_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdio.h> header file. */
#define HAVE_STDIO_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/gmon.h> header file. */
#define HAVE_SYS_GMON_H 1

/* Define to 1 if you have the <sys/mman.h> header file. */
#define HAVE_SYS_MMAN_H 1

/* Define to 1 if you have the <sys/resource.h> header file. */
#define HAVE_SYS_RESOURCE_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <tgmath.h> header file. */
#define HAVE_TGMATH_H 1

/* Define to 1 if you have the <time.h> header file. */
#define HAVE_TIME_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the <varargs.h> header file. */
/* #undef HAVE_VARARGS_H */

/* Define to 1 if you have the <wchar.h> header file. */
#define HAVE_WCHAR_H 1

/* Define to 1 if you have the <wctype.h> header file. */
#define HAVE_WCTYPE_H 1

/* Define to the address where bug reports for this package should be sent. */

/* Define to the full name of this package. */

/* Define to the full name and version of this package. */

/* Define to the one symbol short name of this package. */

/* Define to the home page for this package. */

/* Define to the version of this package. */

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* The size of `char', as computed by sizeof. */
#define SIZEOF_CHAR 1

/* The size of `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of `long', as computed by sizeof. */
#define SIZEOF_LONG 8

/* The size of `long long', as computed by sizeof. */
#define SIZEOF_LONG_LONG 8

/* The size of `ptrdiff_t', as computed by sizeof. */
#define SIZEOF_PTRDIFF_T 8

/* The size of `short', as computed by sizeof. */
#define SIZEOF_SHORT 2

/* The size of `size_t', as computed by sizeof. */
#define SIZEOF_SIZE_T 8

/* The size of `void *', as computed by sizeof. */
#define SIZEOF_VOID_P 8

/* The size of `_Bool', as computed by sizeof. */
#define SIZEOF__BOOL 1

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* whether byteorder is bigendian */
/* #undef WORDS_BIGENDIAN */

/* Define to 1 if `lex' declares `yytext' as a `char *' by default, not a
   `char[]'. */
#define YYTEXT_POINTER 1

/* Define to `long int' if <sys/types.h> does not define. */
/* #undef off_t */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef pid_t */

/* Define to `unsigned int' if <sys/types.h> does not define. */
/* #undef size_t */

/* Bug 1097: do NOT place any includes in this file - it should only contain definitions */

#endif /* UPCR_CONFIG_H */
